### ISSUE TITLE
i can't install new mat plugin

### ISSUE THREAD

**Issue by maneeshdisodia** [MobileAppTracking/phonegap-plugin#6]
Fetching plugin "com.mobileapptracking.matplugin" via plugin registry
Installing "com.mobileapptracking.matplugin" for android
Error during processing of action! Attempting to revert...
Failed to install 'com.mobileapptracking.matplugin':TypeError: Uh oh!
Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:313:15)
    at module.exports.framework.install (/usr/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/android.js:139:35)
    at Object.ActionStack.process (/usr/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/action-stack.js:67:25)
    at handleInstall (/usr/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:575:20)
    at /usr/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:335:28
    at _fulfilled (/usr/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/lib/node_modules/cordova/node_modules/q/q.js:509:49
    at flush (/usr/lib/node_modules/cordova/node_modules/q/q.js:108:17)
TypeError: Uh oh!
Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:313:15)
    at module.exports.framework.install (/usr/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/android.js:139:35)
    at Object.ActionStack.process (/usr/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/action-stack.js:67:25)
    at handleInstall (/usr/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:575:20)
    at /usr/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:335:28
    at _fulfilled (/usr/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/lib/node_modules/cordova/node_modules/q/q.js:509:49
    at flush (/usr/lib/node_modules/cordova/node_modules/q/q.js:108:17)

previously it work. but now it showing this error. my cordova is working fine i can install plugins from apache and various source.
but in MAT case it give me this error. up to version 3.9 and 3.7 its working.
Please look into that.

Thanks
Maneesh

**Comment by john-gu** [comment]
Hi Maneesh,

Our plugin is updated for cordova-android@4.0.0 which is the current default for new Cordova Android projects. If you are on an older version, you may need to do 'cordova platform update android'.

**Comment by maneeshdisodia** [comment]
my cordova is 5.0.0
and i have run this command "cordova platform update android" but still same error

**Comment by john-gu** [comment]
Hi Maneesh,

I was able to repro this error. Removing the previous matplugin version using 'cordova plugin rm' does not remove the Google Play Services dependency so you will have to rm this plugin manually.

On top of that, I had to manually delete the Play Services dependency in 'android.json' under 'installed_plugins'. After that I was able to install com.mobileapptracking.matplugin and build.

**Comment by maneeshdisodia** [comment]
this works. thanks john
